---
- name: Gather information from containerlab EC2 instance
  hosts: containerlab_ec2
  gather_facts: false
  become: true
  vars:
    lab_path: /home/ubuntu/containerlab
  tasks:
    # Pre-validation tasks
    - name: Install docker if not installed
      apt:
        name: docker.io
        state: present

    - name: Install net-tools if not installed
      apt:
        name: net-tools
        state: present

    - name: Install containerlab if not installed
      apt:
        name: containerlab
        state: present
    
    # Deploy new Containerlab
    - name: Destroy previous Containerlab topology
      command: sudo containerlab destroy
      args:
        chdir: "{{ lab_path }}"

    - name: Remove /home/ubuntu/containerlab directory
      file:
        path: "{{ lab_path }}"
        state: absent

    - name: Copy the clabs folder to the host
      copy:
        src: ../resources/containerlab
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: 0755
    
    - name: Deploy Containerlab topology
      command: sudo containerlab deploy
      args:
        chdir: "{{ lab_path }}"
      register: deploy_result

    - name: Wait for deployment to complete
      wait_for:
        path: "{{ lab_path }}"
        timeout: 600
      when: deploy_result is success

  
    # Post-validation tasks
    - name: Show the output of 'sudo containerlab inspect'
      command: sudo containerlab inspect
      args:
        chdir: "{{ lab_path }}"
      register: inspect_output

    - name: Display Containerlab inspect output
      debug:
        var: inspect_output.stdout

    - name: Show listening TCP ports
      command: netstat -tuln
      register: listening_ports

    - name: Display listening TCP ports
      debug:
        var: listening_ports.stdout
